on: 
  push: 
    branches:
      - main
  workflow_dispatch:
name: 🚀 Deploy main website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0-beta
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_pass }}
        server-dir: ${{ secrets.ftp_path }}
